/*
 * SPELL API
 * This is an experimental SPELL-Platform server.  You can find out more about SPELL at [https://spell-plattform.de](https://spell-plattform.de). There is no authentication.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@spell-plattform.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.33
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SpellApi);
  }
}(this, function(expect, SpellApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SpellApi.DefaultApi();
  });

  describe('(package)', function() {
    describe('DefaultApi', function() {
      describe('deleteAttribute', function() {
        it('should call deleteAttribute successfully', function(done) {
          // TODO: uncomment, update parameter values for deleteAttribute call
          /*

          instance.deleteAttribute(attributeId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('deleteDataObject', function() {
        it('should call deleteDataObject successfully', function(done) {
          // TODO: uncomment, update parameter values for deleteDataObject call
          /*

          instance.deleteDataObject(dataObjectId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('exportGraph', function() {
        it('should call exportGraph successfully', function(done) {
          // TODO: uncomment exportGraph call and complete the assertions
          /*

          instance.exportGraph(function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(SpellApi.NotitiaExportFormat);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getOperation', function() {
        it('should call getOperation successfully', function(done) {
          // TODO: uncomment, update parameter values for getOperation call and complete the assertions
          /*

          instance.getOperation(operationId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(SpellApi.OperationObject);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getOperationList', function() {
        it('should call getOperationList successfully', function(done) {
          // TODO: uncomment getOperationList call and complete the assertions
          /*

          instance.getOperationList(function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(SpellApi.OperationList);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('importGraph', function() {
        it('should call importGraph successfully', function(done) {
          // TODO: uncomment, update parameter values for importGraph call
          /*

          instance.importGraph(body, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('loadScenarios', function() {
        it('should call loadScenarios successfully', function(done) {
          // TODO: uncomment, update parameter values for loadScenarios call
          /*

          instance.loadScenarios(body, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('resetDatabase', function() {
        it('should call resetDatabase successfully', function(done) {
          // TODO: uncomment resetDatabase call
          /*

          instance.resetDatabase(function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
