/*
 * SPELL API
 * This is an experimental SPELL-Platform server.  You can find out more about SPELL at [https://spell-plattform.de](https://spell-plattform.de). There is no authentication.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@spell-plattform.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.33
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {OntologyClass} from './OntologyClass';

/**
 * The Attribute model module.
 * @module model/Attribute
 * @version 1.0.0
 */
export class Attribute {
  /**
   * Constructs a new <code>Attribute</code>.
   * @alias module:model/Attribute
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>Attribute</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Attribute} obj Optional instance to populate.
   * @return {module:model/Attribute} The populated <code>Attribute</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Attribute();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('type'))
        obj.type = OntologyClass.constructFromObject(data['type']);
      if (data.hasOwnProperty('label'))
        obj.label = ApiClient.convertToType(data['label'], 'String');
      if (data.hasOwnProperty('value'))
        obj.value = ApiClient.convertToType(data['value'], 'String');
    }
    return obj;
  }
}

/**
 * IRI
 * @member {String} id
 */
Attribute.prototype.id = undefined;

/**
 * @member {module:model/OntologyClass} type
 */
Attribute.prototype.type = undefined;

/**
 * Name
 * @member {String} label
 */
Attribute.prototype.label = undefined;

/**
 * @member {String} value
 */
Attribute.prototype.value = undefined;

