/*
 * SPELL API
 * This is an experimental SPELL-Platform server.  You can find out more about SPELL at [https://spell-plattform.de](https://spell-plattform.de). There is no authentication.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@spell-plattform.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.33
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {Attribute} from './Attribute';
import {OntologyClass} from './OntologyClass';

/**
 * The DataObject model module.
 * @module model/DataObject
 * @version 1.0.0
 */
export class DataObject {
  /**
   * Constructs a new <code>DataObject</code>.
   * @alias module:model/DataObject
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>DataObject</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DataObject} obj Optional instance to populate.
   * @return {module:model/DataObject} The populated <code>DataObject</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new DataObject();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('type'))
        obj.type = OntologyClass.constructFromObject(data['type']);
      if (data.hasOwnProperty('label'))
        obj.label = ApiClient.convertToType(data['label'], 'String');
      if (data.hasOwnProperty('ref'))
        obj.ref = ApiClient.convertToType(data['ref'], 'String');
      if (data.hasOwnProperty('attributes'))
        obj.attributes = ApiClient.convertToType(data['attributes'], [Attribute]);
    }
    return obj;
  }
}

/**
 * IRI
 * @member {String} id
 */
DataObject.prototype.id = undefined;

/**
 * @member {module:model/OntologyClass} type
 */
DataObject.prototype.type = undefined;

/**
 * Name
 * @member {String} label
 */
DataObject.prototype.label = undefined;

/**
 * IRI reference to another DataObject
 * @member {String} ref
 */
DataObject.prototype.ref = undefined;

/**
 * @member {Array.<module:model/Attribute>} attributes
 */
DataObject.prototype.attributes = undefined;

