/*
 * SPELL API
 * This is an experimental SPELL-Platform server.  You can find out more about SPELL at [https://spell-plattform.de](https://spell-plattform.de). There is no authentication.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@spell-plattform.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.33
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The NotitiaTaxonomy model module.
 * @module model/NotitiaTaxonomy
 * @version 1.0.0
 */
export class NotitiaTaxonomy {
  /**
   * Constructs a new <code>NotitiaTaxonomy</code>.
   * @alias module:model/NotitiaTaxonomy
   * @class
   * @extends Object
   */
  constructor() {
  }

  /**
   * Constructs a <code>NotitiaTaxonomy</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/NotitiaTaxonomy} obj Optional instance to populate.
   * @return {module:model/NotitiaTaxonomy} The populated <code>NotitiaTaxonomy</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new NotitiaTaxonomy();
      ApiClient.constructFromObject(data, obj, 'Object');
    }
    return obj;
  }
}
