/*
 * SPELL API
 * This is an experimental SPELL-Platform server.  You can find out more about SPELL at [https://spell-plattform.de](https://spell-plattform.de). There is no authentication.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@spell-plattform.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.33
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The NotitiaEdge model module.
 * @module model/NotitiaEdge
 * @version 1.0.0
 */
export class NotitiaEdge {
  /**
   * Constructs a new <code>NotitiaEdge</code>.
   * @alias module:model/NotitiaEdge
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>NotitiaEdge</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/NotitiaEdge} obj Optional instance to populate.
   * @return {module:model/NotitiaEdge} The populated <code>NotitiaEdge</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new NotitiaEdge();
      if (data.hasOwnProperty('source'))
        obj.source = ApiClient.convertToType(data['source'], 'String');
      if (data.hasOwnProperty('target'))
        obj.target = ApiClient.convertToType(data['target'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} source
 */
NotitiaEdge.prototype.source = undefined;

/**
 * @member {String} target
 */
NotitiaEdge.prototype.target = undefined;

