/*
 * SPELL API
 * This is an experimental SPELL-Platform server.  You can find out more about SPELL at [https://spell-plattform.de](https://spell-plattform.de). There is no authentication.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@spell-plattform.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.33
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {NotitiaEdge} from './NotitiaEdge';
import {NotitiaNode} from './NotitiaNode';

/**
 * The NotitiaExportFormat model module.
 * @module model/NotitiaExportFormat
 * @version 1.0.0
 */
export class NotitiaExportFormat {
  /**
   * Constructs a new <code>NotitiaExportFormat</code>.
   * @alias module:model/NotitiaExportFormat
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>NotitiaExportFormat</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/NotitiaExportFormat} obj Optional instance to populate.
   * @return {module:model/NotitiaExportFormat} The populated <code>NotitiaExportFormat</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new NotitiaExportFormat();
      if (data.hasOwnProperty('nodes'))
        obj.nodes = ApiClient.convertToType(data['nodes'], [NotitiaNode]);
      if (data.hasOwnProperty('links'))
        obj.links = ApiClient.convertToType(data['links'], [NotitiaEdge]);
    }
    return obj;
  }
}

/**
 * @member {Array.<module:model/NotitiaNode>} nodes
 */
NotitiaExportFormat.prototype.nodes = undefined;

/**
 * @member {Array.<module:model/NotitiaEdge>} links
 */
NotitiaExportFormat.prototype.links = undefined;

