/*
 * SPELL API
 * This is an experimental SPELL-Platform server.  You can find out more about SPELL at [https://spell-plattform.de](https://spell-plattform.de). There is no authentication.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@spell-plattform.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.33
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The NotitiaNodeShape model module.
 * @module model/NotitiaNodeShape
 * @version 1.0.0
 */
export class NotitiaNodeShape {
  /**
   * Constructs a new <code>NotitiaNodeShape</code>.
   * @alias module:model/NotitiaNodeShape
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>NotitiaNodeShape</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/NotitiaNodeShape} obj Optional instance to populate.
   * @return {module:model/NotitiaNodeShape} The populated <code>NotitiaNodeShape</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new NotitiaNodeShape();
      if (data.hasOwnProperty('type'))
        obj.type = ApiClient.convertToType(data['type'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} type
 */
NotitiaNodeShape.prototype.type = undefined;

