/*
 * SPELL API
 * This is an experimental SPELL-Platform server.  You can find out more about SPELL at [https://spell-plattform.de](https://spell-plattform.de). There is no authentication.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@spell-plattform.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.33
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {Attribute} from './Attribute';
import {DataObject} from './DataObject';

/**
 * The OperationObject model module.
 * @module model/OperationObject
 * @version 1.0.0
 */
export class OperationObject {
  /**
   * Constructs a new <code>OperationObject</code>.
   * @alias module:model/OperationObject
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>OperationObject</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/OperationObject} obj Optional instance to populate.
   * @return {module:model/OperationObject} The populated <code>OperationObject</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new OperationObject();
      if (data.hasOwnProperty('attributes'))
        obj.attributes = ApiClient.convertToType(data['attributes'], [Attribute]);
      if (data.hasOwnProperty('dataObjects'))
        obj.dataObjects = ApiClient.convertToType(data['dataObjects'], [DataObject]);
    }
    return obj;
  }
}

/**
 * @member {Array.<module:model/Attribute>} attributes
 */
OperationObject.prototype.attributes = undefined;

/**
 * has a
 * @member {Array.<module:model/DataObject>} dataObjects
 */
OperationObject.prototype.dataObjects = undefined;

