/*
 * SPELL API
 * This is an experimental SPELL-Platform server.  You can find out more about SPELL at [https://spell-plattform.de](https://spell-plattform.de). There is no authentication.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@spell-plattform.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.33
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {OperationListNodes} from './OperationListNodes';

/**
 * The OperationList model module.
 * @module model/OperationList
 * @version 1.0.0
 */
export class OperationList {
  /**
   * Constructs a new <code>OperationList</code>.
   * @alias module:model/OperationList
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>OperationList</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/OperationList} obj Optional instance to populate.
   * @return {module:model/OperationList} The populated <code>OperationList</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new OperationList();
      if (data.hasOwnProperty('nodes'))
        obj.nodes = ApiClient.convertToType(data['nodes'], [OperationListNodes]);
    }
    return obj;
  }
}

/**
 * @member {Array.<module:model/OperationListNodes>} nodes
 */
OperationList.prototype.nodes = undefined;

